// Main-thread client for the food worker.
import { signal } from '@preact/signals';
import type { Food } from './nutrients';
import SOURCE_FILES from './sources.json';

/** Food databases the app ships (data files per source, generated by the data build). */
export type Source = keyof typeof SOURCE_FILES;
export const SOURCES = Object.keys(SOURCE_FILES) as Source[];

export type WorkerRequest =
  | { id: number; type: 'init'; files: Record<string, string[]>; sources: string[] }
  | { id: number; type: 'sources'; sources: string[] }
  | { id: number; type: 'warm'; lang: string }
  | { id: number; type: 'custom'; foods: Food[] }
  | { id: number; type: 'boost'; boosts: Record<string, number> }
  | { id: number; type: 'search'; query: string; lang: string; excludePrefix?: string }
  | { id: number; type: 'get'; refs: string[] };

export interface WorkerResponse {
  id: number;
  foods: Food[];
  /** Databases that couldn't be loaded for this request (e.g. offline before first download). */
  failed?: string[];
  error?: string;
}

/** Databases that failed to load on the latest search (shown as a hint; retried automatically). */
export const unavailableSources = signal<string[]>([]);

type Pending = { resolve: (f: Food[]) => void; reject: (e: Error) => void; trackFailures?: boolean };

let worker: Worker | undefined;
let enabledSources: string[] = ['slv'];
let customVisible: Food[] = [];
let nextId = 1;
const pending = new Map<number, Pending>();
const cache = new Map<string, Food>();

type Query = Extract<WorkerRequest, { type: 'search' | 'get' }>;
type WithoutId<T> = T extends unknown ? Omit<T, 'id'> : never;

function call(req: WithoutId<Query>, trackFailures = false): Promise<Food[]> {
  const id = nextId++;
  return new Promise((resolve, reject) => {
    pending.set(id, { resolve, reject, trackFailures });
    getWorker().postMessage({ ...req, id } as WorkerRequest);
  });
}

function getWorker(): Worker {
  if (worker) return worker;
  const w = new Worker(new URL('../worker/foods.worker.ts', import.meta.url), { type: 'module' });
  w.onmessage = (ev: MessageEvent<WorkerResponse>) => {
    const p = pending.get(ev.data.id);
    if (!p) return;
    pending.delete(ev.data.id);
    if (p.trackFailures) unavailableSources.value = ev.data.failed ?? [];
    if (ev.data.error) p.reject(new Error(ev.data.error));
    else {
      for (const f of ev.data.foods) cache.set(f.ref, f);
      p.resolve(ev.data.foods);
    }
  };
  // Resolve against the page so the app works from any base path (e.g. GitHub Pages /repo/).
  const files = Object.fromEntries(
    Object.entries(SOURCE_FILES).map(([s, names]) => [s, names.map((n) => new URL(`data/${n}`, document.baseURI).href)]),
  );
  const init: WorkerRequest = { id: 0, type: 'init', files, sources: enabledSources };
  w.postMessage(init);
  if (customVisible.length) postCustom(w);
  if (Object.keys(userBoosts).length) postBoosts(w);
  return (worker = w);
}

let userBoosts: Record<string, number> = {};

function postBoosts(w: Worker) {
  const msg: WorkerRequest = { id: 0, type: 'boost', boosts: userBoosts };
  w.postMessage(msg);
}

/** Search ranking boosts from the user's history, by food ref. */
export function setUserBoosts(boosts: Record<string, number>): void {
  userBoosts = boosts;
  if (worker) postBoosts(worker);
}

function postCustom(w: Worker) {
  const msg: WorkerRequest = { id: 0, type: 'custom', foods: customVisible };
  w.postMessage(msg);
}

/** Which databases search covers (others still load on demand for old diary entries). */
export function setSources(sources: Source[]): void {
  enabledSources = sources;
  if (worker) {
    const msg: WorkerRequest = { id: 0, type: 'sources', sources };
    worker.postMessage(msg);
  }
}

/** At idle after first paint: load the databases and build the search index for `lang`. */
export function warmUp(lang: string): void {
  const msg: WorkerRequest = { id: 0, type: 'warm', lang };
  getWorker().postMessage(msg);
}

/**
 * Hand the user's custom foods to the search worker. `visible` are searchable;
 * `all` (including deleted ones) stay resolvable for old diary entries.
 */
export function setCustomFoods(visible: Food[], all: Food[]): void {
  for (const f of all) cache.set(f.ref, f);
  customVisible = visible;
  // Don't start the worker (and the food download) just for this; it gets them on creation.
  if (worker) postCustom(worker);
}

/** Search foods; `excludePrefix` (e.g. 'recipe:') leaves out a kind of food, still returning a full page. */
export function searchFoods(query: string, lang: string, excludePrefix?: string): Promise<Food[]> {
  return call({ type: 'search', query, lang, excludePrefix }, true);
}

export async function getFoods(refs: string[]): Promise<Map<string, Food>> {
  const missing = [...new Set(refs)].filter((r) => !cache.has(r));
  if (missing.length) await call({ type: 'get', refs: missing });
  return new Map(refs.filter((r) => cache.has(r)).map((r) => [r, cache.get(r)!]));
}
