// Strings for the sync screens (Settings card and sync sheet), kept out of the first bundle:
// this module loads only with those lazy screens. Same rules as i18n.ts: sv and en, via `ts()`.
import { lang } from './i18n';

const sv = {
  syncTitle: 'Synka med en annan enhet',
  syncCardIntro: 'Kopiera din dagbok och dina inställningar direkt mellan två av dina enheter – utan konto eller server.',
  syncStart: 'Synka',
  syncIntro: 'Öppna Iron Log på båda enheterna, på samma wifi. Starta på den ena enheten och skanna koden med den andra.',
  syncPrivacy: 'Enheterna kopplas ihop direkt och krypterat. Inget skickas till någon server.',
  syncShowCode: 'Starta här (visa kod)',
  syncScanCode: 'Skanna kod',
  syncPreparing: 'Förbereder…',
  syncOfferHint: 'Skanna den här koden med den andra enheten (Inställningar → Synka → Skanna kod).',
  syncThenScanAnswer: 'Skanna sedan svaret från den andra enheten',
  syncScanOfferHint: 'Skanna koden som visas på den andra enheten.',
  syncAnswerHint: 'Skanna den här koden med den första enheten.',
  syncWaiting: 'Väntar på den andra enheten…',
  syncRunning: 'Synkar…',
  syncApplying: 'Sparar ändringarna…',
  syncDone: 'Klart! {in} ändringar hämtade, {out} skickade.',
  syncErrorCode: 'Koden kunde inte läsas. Se till att du skannar koden från Iron Log och försök igen.',
  syncErrorVersion: 'Enheterna har olika versioner av Iron Log. Ladda om appen på båda och försök igen.',
  syncErrorConnect: 'Enheterna fick ingen kontakt. Kontrollera att båda är på samma wifi (inte gästnätverk) och försök igen.',
  syncErrorOther: 'Synkningen misslyckades. Försök igen.',
  syncErrorPartial: 'Anslutningen bröts. En del ändringar hann sparas – synka igen för att få med resten.',
  syncShowSaved: 'Visa det som sparats',
  syncProgress: 'Sparar ändringar… {done} av {total}',
  syncQrLabel: 'QR-kod för att koppla ihop enheterna',
  syncAsText: 'Visa som text',
  syncScanHint: 'Rikta kameran mot QR-koden.',
  syncNoCamera: 'Kameran är inte tillgänglig. Klistra in koden nedan.',
  syncPasteLabel: 'Eller klistra in koden',
  syncUseCode: 'Använd koden',
  copied: 'Kopierad',
};

const en: typeof sv = {
  syncTitle: 'Sync with another device',
  syncCardIntro: 'Copy your diary and settings directly between two of your devices – no account or server.',
  syncStart: 'Sync',
  syncIntro: 'Open Iron Log on both devices, on the same Wi-Fi. Start on one device and scan the code with the other.',
  syncPrivacy: 'The devices connect directly and encrypted. Nothing is sent to any server.',
  syncShowCode: 'Start here (show code)',
  syncScanCode: 'Scan code',
  syncPreparing: 'Preparing…',
  syncOfferHint: 'Scan this code with the other device (Settings → Sync → Scan code).',
  syncThenScanAnswer: 'Then scan the answer from the other device',
  syncScanOfferHint: 'Scan the code shown on the other device.',
  syncAnswerHint: 'Scan this code with the first device.',
  syncWaiting: 'Waiting for the other device…',
  syncRunning: 'Syncing…',
  syncApplying: 'Saving the changes…',
  syncDone: 'Done! {in} changes received, {out} sent.',
  syncErrorCode: 'The code could not be read. Make sure you scan the code from Iron Log and try again.',
  syncErrorVersion: 'The devices run different versions of Iron Log. Reload the app on both and try again.',
  syncErrorConnect: 'The devices could not connect. Check that both are on the same Wi-Fi (not a guest network) and try again.',
  syncErrorOther: 'Sync failed. Try again.',
  syncErrorPartial: 'The connection dropped. Some changes were saved – sync again to get the rest.',
  syncShowSaved: 'Show what was saved',
  syncProgress: 'Saving changes… {done} of {total}',
  syncQrLabel: 'QR code to pair the devices',
  syncAsText: 'Show as text',
  syncScanHint: 'Point the camera at the QR code.',
  syncNoCamera: 'The camera is not available. Paste the code below.',
  syncPasteLabel: 'Or paste the code',
  syncUseCode: 'Use the code',
  copied: 'Copied',
};

export const ts = (key: keyof typeof sv): string => (lang.value === 'en' ? en : sv)[key];
