// Strings for the sync screens (Settings card and sync sheet), kept out of the first bundle:
// this module loads only with those lazy screens. Same rules as i18n.ts: sv and en, via `ts()`.
import { lang, type Lang } from './i18n';

const sv = {
  syncTitle: 'Synka med en annan enhet',
  syncCardIntro: 'Kopiera din dagbok och dina inställningar direkt mellan två av dina enheter – utan konto eller server.',
  syncStart: 'Synka',
  syncIntro: 'Öppna Iron Log på båda enheterna, på samma wifi. Starta på den ena enheten och skanna koden med den andra.',
  syncPrivacy: 'Enheterna kopplas ihop direkt och krypterat. Inget skickas till någon server.',
  syncShowCode: 'Starta här (visa kod)',
  syncScanCode: 'Skanna kod',
  syncPreparing: 'Förbereder…',
  syncOfferHint: 'Skanna den här koden med den andra enheten (Inställningar → Synka → Skanna kod).',
  syncThenScanAnswer: 'Skanna sedan svaret från den andra enheten',
  syncScanOfferHint: 'Skanna koden som visas på den andra enheten.',
  syncAnswerHint: 'Skanna den här koden med den första enheten.',
  syncWaiting: 'Väntar på den andra enheten…',
  syncRunning: 'Synkar…',
  syncApplying: 'Sparar ändringarna…',
  syncDone: 'Klart! {in} ändringar hämtade, {out} skickade.',
  syncErrorCode: 'Koden kunde inte läsas. Se till att du skannar koden från Iron Log och försök igen.',
  syncErrorVersion: 'Enheterna har olika versioner av Iron Log. Ladda om appen på båda och försök igen.',
  syncErrorConnect: 'Enheterna fick ingen kontakt. Kontrollera att båda är på samma wifi (inte gästnätverk) och försök igen.',
  syncErrorOther: 'Synkningen misslyckades. Försök igen.',
  syncErrorPartial: 'Anslutningen bröts. En del ändringar hann sparas – synka igen för att få med resten.',
  syncShowSaved: 'Visa det som sparats',
  syncProgress: 'Sparar ändringar… {done} av {total}',
  syncQrLabel: 'QR-kod för att koppla ihop enheterna',
  syncAsText: 'Visa som text',
  syncScanHint: 'Rikta kameran mot QR-koden.',
  syncNoCamera: 'Kameran är inte tillgänglig. Klistra in koden nedan.',
  syncPasteLabel: 'Eller klistra in koden',
  syncUseCode: 'Använd koden',
  copied: 'Kopierad',
};

const en: typeof sv = {
  syncTitle: 'Sync with another device',
  syncCardIntro: 'Copy your diary and settings directly between two of your devices – no account or server.',
  syncStart: 'Sync',
  syncIntro: 'Open Iron Log on both devices, on the same Wi-Fi. Start on one device and scan the code with the other.',
  syncPrivacy: 'The devices connect directly and encrypted. Nothing is sent to any server.',
  syncShowCode: 'Start here (show code)',
  syncScanCode: 'Scan code',
  syncPreparing: 'Preparing…',
  syncOfferHint: 'Scan this code with the other device (Settings → Sync → Scan code).',
  syncThenScanAnswer: 'Then scan the answer from the other device',
  syncScanOfferHint: 'Scan the code shown on the other device.',
  syncAnswerHint: 'Scan this code with the first device.',
  syncWaiting: 'Waiting for the other device…',
  syncRunning: 'Syncing…',
  syncApplying: 'Saving the changes…',
  syncDone: 'Done! {in} changes received, {out} sent.',
  syncErrorCode: 'The code could not be read. Make sure you scan the code from Iron Log and try again.',
  syncErrorVersion: 'The devices run different versions of Iron Log. Reload the app on both and try again.',
  syncErrorConnect: 'The devices could not connect. Check that both are on the same Wi-Fi (not a guest network) and try again.',
  syncErrorOther: 'Sync failed. Try again.',
  syncErrorPartial: 'The connection dropped. Some changes were saved – sync again to get the rest.',
  syncShowSaved: 'Show what was saved',
  syncProgress: 'Saving changes… {done} of {total}',
  syncQrLabel: 'QR code to pair the devices',
  syncAsText: 'Show as text',
  syncScanHint: 'Point the camera at the QR code.',
  syncNoCamera: 'The camera is not available. Paste the code below.',
  syncPasteLabel: 'Or paste the code',
  syncUseCode: 'Use the code',
  copied: 'Copied',
};

// Beta translations (machine-assisted, awaiting native-speaker review); missing keys use English.
const da: Partial<typeof sv> = {
  syncTitle: 'Synkroniser med en anden enhed',
  syncCardIntro: 'Kopiér din dagbog og dine indstillinger direkte mellem to af dine enheder – uden konto eller server.',
  syncStart: 'Synkroniser',
  syncIntro: 'Åbn Iron Log på begge enheder, på samme wifi. Start på den ene enhed, og scan koden med den anden.',
  syncPrivacy: 'Enhederne forbindes direkte og krypteret. Intet sendes til nogen server.',
  syncShowCode: 'Start her (vis kode)',
  syncScanCode: 'Scan kode',
  syncPreparing: 'Forbereder…',
  syncOfferHint: 'Scan denne kode med den anden enhed (Indstillinger → Synkroniser → Scan kode).',
  syncThenScanAnswer: 'Scan derefter svaret fra den anden enhed',
  syncScanOfferHint: 'Scan koden, der vises på den anden enhed.',
  syncAnswerHint: 'Scan denne kode med den første enhed.',
  syncWaiting: 'Venter på den anden enhed…',
  syncRunning: 'Synkroniserer…',
  syncApplying: 'Gemmer ændringerne…',
  syncDone: 'Færdig! {in} ændringer modtaget, {out} sendt.',
  syncErrorCode: 'Koden kunne ikke læses. Sørg for at scanne koden fra Iron Log, og prøv igen.',
  syncErrorVersion: 'Enhederne kører forskellige versioner af Iron Log. Genindlæs appen på begge, og prøv igen.',
  syncErrorConnect: 'Enhederne fik ikke forbindelse. Tjek, at begge er på samme wifi (ikke et gæstenetværk), og prøv igen.',
  syncErrorOther: 'Synkroniseringen mislykkedes. Prøv igen.',
  syncErrorPartial: 'Forbindelsen blev afbrudt. Nogle ændringer nåede at blive gemt – synkroniser igen for at få resten med.',
  syncShowSaved: 'Vis det gemte',
  syncProgress: 'Gemmer ændringer… {done} af {total}',
  syncQrLabel: 'QR-kode til at forbinde enhederne',
  syncAsText: 'Vis som tekst',
  syncScanHint: 'Ret kameraet mod QR-koden.',
  syncNoCamera: 'Kameraet er ikke tilgængeligt. Indsæt koden nedenfor.',
  syncPasteLabel: 'Eller indsæt koden',
  syncUseCode: 'Brug koden',
  copied: 'Kopieret',
};

const de: Partial<typeof sv> = {
  syncTitle: 'Mit einem anderen Gerät synchronisieren',
  syncCardIntro: 'Tagebuch und Einstellungen direkt zwischen zwei deiner Geräte kopieren – ohne Konto oder Server.',
  syncStart: 'Synchronisieren',
  syncIntro: 'Öffne Iron Log auf beiden Geräten im selben WLAN. Starte auf einem Gerät und scanne den Code mit dem anderen.',
  syncPrivacy: 'Die Geräte verbinden sich direkt und verschlüsselt. Nichts wird an einen Server gesendet.',
  syncShowCode: 'Hier starten (Code zeigen)',
  syncScanCode: 'Code scannen',
  syncPreparing: 'Wird vorbereitet…',
  syncOfferHint: 'Scanne diesen Code mit dem anderen Gerät (Einstellungen → Synchronisieren → Code scannen).',
  syncThenScanAnswer: 'Scanne dann die Antwort des anderen Geräts',
  syncScanOfferHint: 'Scanne den Code, der auf dem anderen Gerät angezeigt wird.',
  syncAnswerHint: 'Scanne diesen Code mit dem ersten Gerät.',
  syncWaiting: 'Warte auf das andere Gerät…',
  syncRunning: 'Synchronisiere…',
  syncApplying: 'Änderungen werden gespeichert…',
  syncDone: 'Fertig! {in} Änderungen empfangen, {out} gesendet.',
  syncErrorCode: 'Der Code konnte nicht gelesen werden. Scanne den Code aus Iron Log und versuche es erneut.',
  syncErrorVersion: 'Die Geräte haben verschiedene Iron-Log-Versionen. Lade die App auf beiden neu und versuche es erneut.',
  syncErrorConnect: 'Die Geräte konnten sich nicht verbinden. Prüfe, ob beide im selben WLAN sind (kein Gastnetz), und versuche es erneut.',
  syncErrorOther: 'Die Synchronisierung ist fehlgeschlagen. Versuche es erneut.',
  syncErrorPartial: 'Die Verbindung brach ab. Einige Änderungen wurden gespeichert – synchronisiere erneut, um den Rest zu erhalten.',
  syncShowSaved: 'Gespeichertes anzeigen',
  syncProgress: 'Änderungen werden gespeichert… {done} von {total}',
  syncQrLabel: 'QR-Code zum Verbinden der Geräte',
  syncAsText: 'Als Text zeigen',
  syncScanHint: 'Richte die Kamera auf den QR-Code.',
  syncNoCamera: 'Die Kamera ist nicht verfügbar. Füge den Code unten ein.',
  syncPasteLabel: 'Oder Code einfügen',
  syncUseCode: 'Code verwenden',
  copied: 'Kopiert',
};

const fi: Partial<typeof sv> = {
  syncTitle: 'Synkronoi toisen laitteen kanssa',
  syncCardIntro: 'Kopioi päiväkirja ja asetukset suoraan kahden laitteesi välillä – ilman tiliä tai palvelinta.',
  syncStart: 'Synkronoi',
  syncIntro: 'Avaa Iron Log molemmissa laitteissa samassa wifissä. Aloita toisella laitteella ja skannaa koodi toisella.',
  syncPrivacy: 'Laitteet yhdistyvät suoraan ja salattuina. Mitään ei lähetetä palvelimelle.',
  syncShowCode: 'Aloita tästä (näytä koodi)',
  syncScanCode: 'Skannaa koodi',
  syncPreparing: 'Valmistellaan…',
  syncOfferHint: 'Skannaa tämä koodi toisella laitteella (Asetukset → Synkronoi → Skannaa koodi).',
  syncThenScanAnswer: 'Skannaa sitten toisen laitteen vastaus',
  syncScanOfferHint: 'Skannaa toisella laitteella näkyvä koodi.',
  syncAnswerHint: 'Skannaa tämä koodi ensimmäisellä laitteella.',
  syncWaiting: 'Odotetaan toista laitetta…',
  syncRunning: 'Synkronoidaan…',
  syncApplying: 'Tallennetaan muutoksia…',
  syncDone: 'Valmis! {in} muutosta vastaanotettu, {out} lähetetty.',
  syncErrorCode: 'Koodia ei voitu lukea. Varmista, että skannaat Iron Login koodin, ja yritä uudelleen.',
  syncErrorVersion: 'Laitteissa on eri Iron Log -versiot. Lataa sovellus uudelleen molemmissa ja yritä uudelleen.',
  syncErrorConnect: 'Laitteet eivät saaneet yhteyttä. Tarkista, että molemmat ovat samassa wifissä (ei vierasverkossa), ja yritä uudelleen.',
  syncErrorOther: 'Synkronointi epäonnistui. Yritä uudelleen.',
  syncErrorPartial: 'Yhteys katkesi. Osa muutoksista ehdittiin tallentaa – synkronoi uudelleen saadaksesi loput.',
  syncShowSaved: 'Näytä tallennetut',
  syncProgress: 'Tallennetaan muutoksia… {done}/{total}',
  syncQrLabel: 'QR-koodi laitteiden yhdistämiseen',
  syncAsText: 'Näytä tekstinä',
  syncScanHint: 'Suuntaa kamera QR-koodiin.',
  syncNoCamera: 'Kamera ei ole käytettävissä. Liitä koodi alle.',
  syncPasteLabel: 'Tai liitä koodi',
  syncUseCode: 'Käytä koodia',
  copied: 'Kopioitu',
};

const so: Partial<typeof sv> = {
  syncTitle: 'La jaanqaad qalab kale',
  syncCardIntro: 'Si toos ah u koobi buuggaaga iyo dejintaada laba ka mid ah qalabkaaga – akoon iyo server la’aan.',
  syncStart: 'Jaanqaad',
  syncIntro: 'Ka fur Iron Log labada qalab, isla wifi-ga. Ka bilow mid, kan kalena ku iskaan garee koodka.',
  syncPrivacy: 'Qalabku si toos ah oo sir ah ayay isku xirmaan. Waxba looma diro server.',
  syncShowCode: 'Halkan ka bilow (muuji koodka)',
  syncScanCode: 'Iskaan garee koodka',
  syncPreparing: 'Waa la diyaarinayaa…',
  syncOfferHint: 'Koodkan ku iskaan garee qalabka kale (Dejinta → Jaanqaad → Iskaan garee koodka).',
  syncThenScanAnswer: 'Kadib iskaan garee jawaabta qalabka kale',
  syncScanOfferHint: 'Iskaan garee koodka ka muuqda qalabka kale.',
  syncAnswerHint: 'Koodkan ku iskaan garee qalabka koowaad.',
  syncWaiting: 'Waxaa la sugayaa qalabka kale…',
  syncRunning: 'Waa la jaanqaadayaa…',
  syncApplying: 'Isbeddellada waa la keydinayaa…',
  syncDone: 'Waa dhammaatay! {in} isbeddel ayaa la helay, {out} ayaa la diray.',
  syncErrorCode: 'Koodka lama akhriyi karo. Hubi inaad iskaan garaynayso koodka Iron Log oo isku day mar kale.',
  syncErrorVersion: 'Qalabku waxay leeyihiin noocyo kala duwan oo Iron Log ah. Dib u soo rar app-ka labadaba oo isku day mar kale.',
  syncErrorConnect: 'Qalabku isma xirmi karin. Hubi in labaduba ku jiraan isla wifi-ga (ma aha shabakad marti) oo isku day mar kale.',
  syncErrorOther: 'Jaanqaadku wuu fashilmay. Isku day mar kale.',
  syncErrorPartial: 'Xiriirku wuu go’ay. Isbeddellada qaar ayaa la keydiyay – mar kale jaanqaad si aad u hesho inta harsan.',
  syncShowSaved: 'Muuji waxa la keydiyay',
  syncProgress: 'Isbeddellada waa la keydinayaa… {done} ka mid ah {total}',
  syncQrLabel: 'Koodka QR ee isku xirka qalabka',
  syncAsText: 'Muuji qoraal ahaan',
  syncScanHint: 'U jeedi kaamerada koodka QR.',
  syncNoCamera: 'Kaamerada lama heli karo. Hoos ku dheji koodka.',
  syncPasteLabel: 'Ama dheji koodka',
  syncUseCode: 'Isticmaal koodka',
  copied: 'Waa la koobiyay',
};

const packs: Record<Lang, Partial<typeof sv>> = { sv, en, da, de, fi, so };

export const ts = (key: keyof typeof sv): string => packs[lang.value][key] ?? en[key];
